version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  sync-github-with-gitlabci:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: ls
            - run: git remote add gitlabci git@gitlab.com:abdoulayeke12/cv-keita-abdoulaye.git
            - run: git fetch --all
            - run: git status
            - run: git log --all --decorate --oneline --graph
            - run: git branch --all
            - run: git checkout gitlabci/master
            - run: git rebase origin/master
            - run: git push gitlabci HEAD:master
            - run: git log --all --decorate --oneline --graph
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    sync-github-with-gitlabci:
      jobs:
        - sync-github-with-gitlabci
    build-and-test:
      jobs:
        - build-and-test